layout_spectrum: 0.9103943
color:
  saturation: 0.7921147
  lightness: 0.6236559
  brandStrength: 0.2544803
  brandColors:
    - '#201F1A'
    - '#FFFFFF'
    - '#7E7D67'
    - '#7B0827'
    - '#E3B4A0'
  rhythmicContrast: 0.2598566
typography_spectrum: 0.09498208
name: Erini lood
